name: 🔗 GHA
on:
  workflow_dispatch:

  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "**/*.png"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/CODEOWNERS"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**/README.md"
      - "**/*.png"
      - "**/LICENSE"
      - ".github/ISSUE_TEMPLATE/*"
      - ".github/CODEOWNERS"

env:
  GODOT_VERSION: 4.1

jobs:
  static-checks:
    name: 📊 Static checks
    uses: ./.github/workflows/static-checks.yml
  
  gdextension-build:
    name: ⚙️ GDExtension
    needs: static-checks
    uses: ./.github/workflows/gdextension.yml
    with:
      fullbuild: ${{ github.event_name == 'workflow_dispatch' }}
      godot_version: 4.1
